// Generated by https://pagedraw.io/pages/15463
import React from 'react';
import './display_scren.css';


export default class Display_scren extends React.Component {
  render() {
    return (
      <div className="display_scren-display_scren-2">
          <div className="display_scren-0">
              <div className="display_scren-save_the_water_-3">
                  Save the Water
              </div>
          </div>
          <div className="display_scren-1">
              <div className="display_scren-1-0">
                  <div className="display_scren-1-0-0">
                      <img src="https://ucarecdn.com/8f31fdb1-e872-476d-9697-4869c48c1bcc/" className="display_scren-image_3" /> 
                  </div>
              </div>
              <div className="display_scren-1-1">
                  <div className="display_scren-1-1-0">
                      <div className="display_scren-about_-9">About</div>
                  </div>
                  <div className="display_scren-1-1-1">
                      <div className="display_scren-world_water_day_marked_each_year_on_march_2">
                          {"World Water Day, marked each year on March 22, is an opportunity to celebrate the immense progress made to improve access to clean water: between 1990 and 2015, 2.3 billion people gained access to a better, safer source of water. "}
                      </div>
                  </div>
              </div>
          </div>
          <div className="display_scren-2">
              <div className="display_scren-2-0">
                  <div className="display_scren-2-0-0">
                      <div className="display_scren-average_impact_rating_-9">
                          Average Impact Rating
                      </div>
                  </div>
              </div>
              <div className="display_scren-oval_2">
                  <div className="display_scren-2-1-0">
                      <div className="display_scren-9">{"98%"}</div>
                  </div>
              </div>
              <div className="display_scren-2-2">
                  <div className="display_scren-2-2-0">
                      <div className="display_scren-rectangle-1">
                          <div className="display_scren-2-2-0-0-0">
                              <div className="display_scren-donate_-3">Donate</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
