// Generated by https://pagedraw.io/pages/15463
import React from 'react';
import './home.css';


export default class Home extends React.Component {
  render() {
    return (
      <div className="home-home-3">
          <div className="home-0">
              <div className="home-0-0">
                  <div className="home-0-0-0">
                      <img src="https://ucarecdn.com/a26d120c-d597-44d4-9de8-1619792fc8f8/" className="home-image_2" /> 
                  </div>
                  <div className="home-0-0-1">
                      <div className="home-non-profit_portal_-4">
                          Non-Profit Portal 
                      </div>
                  </div>
                  <div className="home-0-0-2">
                      <div className="home-rectangle-4">
                          <div className="home-0-0-2-0-0">
                              <div className="home-create_account_-7">
                                  Create Account 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="home-0-0-3">
                      <div className="home-rectangle-40">
                          <div className="home-0-0-3-0-0">
                              <div className="home-login_-9">Login</div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="home-line-0" /> 
              <div className="home-0-2">
                  <div className="home-0-2-0">
                      <img src="https://ucarecdn.com/c839ce3b-22e7-4ec3-b513-759812ee6f13/" className="home-image-4" /> 
                  </div>
                  <div className="home-0-2-1">
                      <div className="home-donor_portal_-5">Donor Portal </div>
                  </div>
                  <div className="home-0-2-2">
                      <div className="home-rectangle-48">
                          <div className="home-0-2-2-0-0">
                              <div className="home-create_account_-8">
                                  Create Account 
                              </div>
                          </div>
                      </div>
                  </div>
                  <div className="home-0-2-3">
                      <div className="home-rectangle-2">
                          <div className="home-0-2-3-0-0">
                              <div className="home-login_-1">Login</div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
