// Generated by https://pagedraw.io/pages/15463
import React from 'react';
import './ngoprofile.css';


export default class Ngoprofile extends React.Component {
  render() {
    return (
      <div className="ngoprofile-ngoprofile-0">
          <div className="ngoprofile-0">
              <div className="ngoprofile-0-0">
                  <div className="ngoprofile-0-0-0">
                      <div className="ngoprofile-account_information_-2">
                          Account Information 
                      </div>
                  </div>
                  <div className="ngoprofile-0-0-1">
                      <div className="ngoprofile-0-0-1-0">
                          <div className="ngoprofile-0-0-1-0-0">
                              <div className="ngoprofile-name_of_organization_-9">
                                  Name of Organization 
                              </div>
                          </div>
                      </div>
                      <input type="text" placeholder="Placeholder" className="ngoprofile-text_input-7" /> 
                  </div>
                  <div className="ngoprofile-0-0-2">
                      <div className="ngoprofile-0-0-2-0">
                          <div className="ngoprofile-0-0-2-0-0">
                              <div className="ngoprofile-sector_-9">Sector </div>
                          </div>
                      </div>
                      <input type="text" placeholder="Placeholder" className="ngoprofile-text_input-6" /> 
                  </div>
              </div>
              <div className="ngoprofile-0-1">
                  <div className="ngoprofile-0-1-0">
                      <div className="ngoprofile-oval-1">
                          <div className="ngoprofile-0-1-0-0-0">
                              <div className="ngoprofile-rectangle_2" /> 
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="ngoprofile-1">
              <div className="ngoprofile-1-0">
                  <div className="ngoprofile-1-0-0">
                      <div className="ngoprofile-email_-1">Email </div>
                  </div>
              </div>
              <input type="text" placeholder="Placeholder" className="ngoprofile-text_input-1" /> 
          </div>
          <div className="ngoprofile-2">
              <div className="ngoprofile-2-0">
                  <div className="ngoprofile-2-0-0">
                      <div className="ngoprofile-location_-9">Location </div>
                  </div>
              </div>
              <input type="text" placeholder="Placeholder" className="ngoprofile-text_input-0" /> 
          </div>
          <div className="ngoprofile-3">
              <div className="ngoprofile-3-0">
                  <div className="ngoprofile-3-0-0">
                      <div className="ngoprofile-about_-0">About</div>
                  </div>
              </div>
              <div className="ngoprofile-3-1">
                  <div className="ngoprofile-3-1-0">
                      <input type="text" placeholder="Placeholder" className="ngoprofile-text_input-9" /> 
                  </div>
              </div>
              <div className="ngoprofile-3-2">
                  <div className="ngoprofile-3-2-0">
                      <div className="ngoprofile-create_account_-7">
                          Create Account 
                      </div>
                  </div>
                  <div className="ngoprofile-3-2-1">
                      <div className="ngoprofile-rectangle-9">
                          <div className="ngoprofile-3-2-1-0-0">
                              <div className="ngoprofile-add_a_bank_account_-7">
                                  Add a bank Account
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    );
  }
};
