// Generated by https://pagedraw.io/pages/15463
import React from 'react';
import './success.css';


export default class Success extends React.Component {
  render() {
    return (
      <div className="success-success-5">
          <div className="success-0" /> 
          <div className="success-1">
              <div className="success-1-0" /> 
              <div className="success-zip-9">Save The Water</div>
              <div className="success-1-2" /> 
          </div>
          <div className="success-2" /> 
          <div className="success-3">
              <img src="https://ucarecdn.com/89d8c931-6cd2-45a1-8d63-ddfe7aed2fdb/" className="success-image_4" /> 
          </div>
          <div className="success-4" /> 
          <div className="success-5">
              <div className="success-zip-3">
                  {"World Water Day, marked each year on March 22, is an opportunity to celebrate the immense progress made to improve access to clean water: between 1990 and 2015, 2.3 billion people gained access to a better, safer source of water is being Processed"}
              </div>
          </div>
          <div className="success-6" /> 
          <div className="success-7">
              <div className="success-line_2" /> 
          </div>
          <div className="success-8" /> 
          <div className="success-9">
              <div className="success-zip-0">Average Impact Rating </div>
          </div>
          <div className="success-10" /> 
          <div className="success-11">
              <div className="success-oval_3">
                  <div className="success-11-0-0">
                      <div className="success-80">{"80%"}</div>
                  </div>
              </div>
          </div>
          <div className="success-12" /> 
          <div className="success-13">
              <div className="success-13-0" /> 
              <div className="success-rectangle-8">
                  <div className="success-13-1-0">
                      <div className="success-sign_in-9">Donate</div>
                  </div>
              </div>
              <div className="success-13-2" /> 
          </div>
          <div className="success-14" /> 
      </div>
    );
  }
};
